### ISSUE TITLE
文件夹路径显示有问题

### ISSUE THREAD

**Issue by doer-zwl** [niT-Tin/abws#1]
![image](https://github.com/niT-Tin/abws/assets/88566924/8317631f-c196-4549-b2f0-1b0a36de8e35)

**Comment by niT-Tin** [comment]
一开始没注意到这个问题，谢谢你的提醒，基本功能已经实现。

https://github.com/niT-Tin/abws/assets/73155828/5e9658f4-4cfd-4807-9985-65ae58691678

**Comment by doer-zwl** [comment]
谢谢！
